[versions]
kotlin = "1.7.0"
compose = "1.2.1"
corektx = "1.9.0"
appcompat = "1.5.1"
activity = "1.6.0"
lifecycle = "2.5.1"

material = "1.6.1"
junit = "4.13.2"
androidx-test-junit = "1.1.3"
androidx-test-espresso = "3.4.0"

gradleplugin = "7.3.0"

dagger-hilt = "2.44"
flipper = "0.164.0"
soloader = "0.10.4"
okhttp = "4.10.0"

google-services = "4.3.14"
crashlytics = "2.9.2"
firebase = "30.4.1"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "gradleplugin" }
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "corektx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-kapt = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger-hilt" }

google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
firebase = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlyrics = { module = "com.google.firebase:firebase-analytics-ktx" }

[bundles]
compose = ["compose-ui", "compose-ui-tooling", "compose-activity", "compose-animation", "compose-viewmodel", "compose-material", "compose-runtime", "compose-ui-tooling-preview"]
compose-test = ["compose-junit"]
compose-android-test = ["compose-ui-test"]
android-test = ["androidx-test-junit", "androidx-test-espresso"]
okhttp = ["okhttp", "okhttp-logging-interceptor"]
flipper = ["flipper", "soloader"]
firebase = ["firebase-analytics", "firebase-crashlyrics"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
