name: Makers Builder

on:
    push:
        branches: [ develop, master ]

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build:
        name: Generate APK
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Gradle cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Change gradlew permissions
                run: chmod +x ./gradlew

            -   name: Lint Check
                run: ./gradlew ktlintCheck

            -   name: Build debug APK
                run: ./gradlew assembleDebug --stacktrace

            -   name: On Failed, Notify in Slack
                if: ${{ failure() }}
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_COLOR: '#ff0000'
                    SLACK_ICON: https://user-images.githubusercontent.com/59532818/197379133-676094c1-d544-4784-b582-60e061f69d31.png?size=48
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                    SLACK_TITLE: 'Makers checks have failed ⚠️🚫'
                    MSG_MINIMAL: true
                    SLACK_USERNAME: Makers Android
                    SLACK_MESSAGE: '버그 저리가'

            -   name: Upload APK
                if: ${{ success() }}
                uses: MeilCli/slack-upload-file@v1
                with:
                    slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
                    channels: ${{ secrets.SLACK_CHANNEL_ID }}
                    file_path: 'app/build/outputs/apk/debug/app-debug.apk'
                    file_name: 'Makers.apk'
                    file_type: 'apk'
                    initial_comment: '${{ github.ref }} APK Distributed on Slack'